name: Build AAB and APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # splash hatasını fix
      - name: Fix splash crash
        run: |
          sed -i 's/@drawable\/splash/@android:color\/white/g' app/src/main/res/values/*.xml || true
          sed -i 's/@drawable\/splash/@android:color\/white/g' app/src/main/res/values-night/*.xml || true

      # 🔥 DOĞRU BUILD
      - name: Build APK & AAB
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
