name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: unzip "Android dua 90.zip" -d project

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Permission
        run: chmod +x project/gradlew

      - name: Build AAB
        working-directory: project
        run: ./gradlew bundleRelease

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: project/app/build/outputs/bundle/release/*.aab
